server:
  port: 80
spring:
  application:
    name: wwang-blog
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zeclm6s4bqhu3c453o.mysql.rds.aliyuncs.com:3306/blog?useUnicode=true&&characterEncoding=utf8&serverTimezone=UTC
    username: wwang
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 8
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        url-pattern: "/druid/*"
        login-username: root
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    cache: false

  jpa:
    show-sql: true
    # 改变实体映射策略，驼峰允许
    hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: net.wwang.blog.model

springfox.documentation.swagger.v2.path: /api-docs
swagger:
show: true

logging:
  config: src/main/resources/logback-spring.xml

